apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsendt-soeknad
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: internal/isalive
  readiness:
    initialDelay: 5
    path: internal/isready
  prometheus:
    enabled: true
    path: internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: innsendt-soeknad-v2
        tier: db-g1-small
        databases:
          - name: innsendte-soeknader
            envVarPrefix: DB
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: KAFKA_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
    - name: SOEKNAD_DOMAIN_URL
      value: https://etterlatte.intern.dev.nav.no
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: "dev-fss:pdl:pdl-api"
    - name: KODEVERK_URL
      value: "https://kodeverk-api.nav.no/api/v1/kodeverk"
    - name: KODEVERK_CLIENT_ID
      value: dev-gcp.team-rocket.kodeverk-api
    - name: KRR_ENDPOINT_URL
      value: "http://digdir-krr-proxy.team-rocket/rest/v1/"
    - name: KRR_SCOPE
      value: "api://dev-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_AUDIENCE
      value: "dev-gcp:team-rocket:digdir-krr-proxy"
    - name: NAV_CONSUMER_ID
      value: "srvbarnepensjon"
  accessPolicy:
    outbound:
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: kodeverk-api
          namespace: team-rocket
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no # må gå mot prod i dev se https://nav-it.slack.com/archives/C06FK6V74JE/p1723795352459339?thread_ts=1723788766.141209&cid=C06FK6V74JE
    inbound:
      rules:
        - application: barnepensjon-ui
        - application: omstillingsstoenad-ui