apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsendt-soeknad
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        name: innsendt-soeknad-v2
        databases:
          - name: innsendte-soeknader
            envVarPrefix: DB
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: KAFKA_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
    - name: SOEKNAD_DOMAIN_URL
      value: https://etterlatte.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: selvbetjening-api