apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsendt-soeknad
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: internal/isalive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: internal/isready
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: innsendt-soeknad-v2
        diskAutoresize: true
        diskType: SSD
        autoBackupHour: 1
        tier: db-custom-1-3840
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 2
        databases:
          - name: innsendte-soeknader
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "100"
  resources:
    requests:
      cpu: 25m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.etterlatteytelser
    - name: KAFKA_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
    - name: SOEKNAD_DOMAIN_URL
      value: https://nav.no
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: "prod-fss:pdl:pdl-api"
    - name: KODEVERK_URL
      value: "http://kodeverk-api.team-rocket/api/v1/kodeverk"
    - name: KODEVERK_CLIENT_ID
      value: prod-gcp.team-rocket.kodeverk-api
    - name: KRR_ENDPOINT_URL
      value: "http://digdir-krr-proxy.team-rocket/rest/v1/"
    - name: KRR_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_AUDIENCE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"
    - name: NAV_CONSUMER_ID
      value: "srvbarnepensjon"
  accessPolicy:
    outbound:
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: kodeverk-api
          namespace: team-rocket
      external:
        - host: pdl-api.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: barnepensjon-ui
        - application: omstillingsstoenad-ui