apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsendt-soeknad
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: innsendt-soeknad-v2
        diskAutoresize: true
        diskType: SSD
        autoBackupHour: 1
        tier: db-custom-1-3840
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 2
        databases:
          - name: innsendte-soeknader
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "100"
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.etterlatteytelser
    - name: KAFKA_UTKAST_TOPIC
      value: min-side.aapen-utkast-v1
    - name: SOEKNAD_DOMAIN_URL
      value: https://nav.no
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: "prod-fss:pdl:pdl-api"
    - name: KRR_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_AUDIENCE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"
    - name: KODEVERK_URL
      value: "https://kodeverk-api.nav.no/api/v1/kodeverk"
  accessPolicy:
    inbound:
      rules:
        - application: selvbetjening-api