apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: journalfoer-soeknad
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.etterlatteytelser
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: PDF_URL
      value: "http://ey-pdfgen/api/v1/genpdf/eypdfgen"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost"
    - name: AZURE_DOKARKIV_SCOPE
      value: "api://prod-fss.teamdokumenthandtering.dokarkiv/.default"
  accessPolicy:
    outbound:
      rules:
        - application: ey-pdfgen
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
