version: 2
updates:
  # ==============
  # KOTLIN BACKEND
  # ==============

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"

  # =====================
  # FRONTEND BARNEPENSJON OG OMSTILLINGSSTØNAD
  # =====================

  - package-ecosystem: "npm"
    directories:
      - "/apps/barnepensjon-ui"
      - "/apps/omstillingsstoenad-ui"
      - "/apps/selvbetjening-ui"
      - "/apps/etterlatte-node-server"
      - "/apps/brukerdialog-sanity"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"

  # ==============
  # GITHUB ACTIONS
  # ==============

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"

  # ===========
  # DOCKERFILES
  # ===========

  - package-ecosystem: "docker"
    directory: "/docker/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/apps/etterlatte-node-server"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
