apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-ui
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - https://etterlatte.dev.nav.no/gjenlevendepensjon/soknad
  liveness:
    path: /gjenlevendepensjon/soknad/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /gjenlevendepensjon/soknad/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /gjenlevendepensjon/soknad/metrics
  tokenx:
    enabled: true
  idporten:
    enabled: true
    clientUri: https://www.dev.nav.no
    frontchannelLogoutPath: /gjenlevendepensjon/soknad/logout
    postLogoutRedirectURIs:
      - https://etterlatte.dev.nav.no/gjenlevendepensjon/soknad/logout/callback
    accessTokenLifetime: 3600
    sessionLifetime: 3600
  envFrom:
    - secret: redis-password
    - secret: session-encrypt-key
  env:
    - name: API_URL
      value: http://selvbetjening-api
    - name: REDIS_HOST
      value: selvbetjening-redis.etterlatte.svc.cluster.local
    - name: SELVBETJENING_AUDIENCE
      value: dev-gcp:etterlatte:selvbetjening-api
    - name: NODE_LOG_LEVEL
      value: info
    - name: IDPORTEN_POST_LOGOUT_REDIRECT_URI
      value: https://etterlatte.dev.nav.no/gjenlevendepensjon/soknad/logout/callback
    - name: LOGINSERVICE_URL
      value: https://loginservice.dev.nav.no/login?redirect=https://etterlatte.dev.nav.no/gjenlevendepensjon/soknad
    - name: LOGINSERVICE_LOGOUT_URL
      value: https://loginservice.dev.nav.no/slo
  accessPolicy:
    outbound:
      external:
        - host: loginservice.dev.nav.no
        - host: dekoratoren.dev.nav.no
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: selvbetjening-api
        - application: selvbetjening-redis