apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: brukerdialog-frontend-alerts
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  groups:
    - name: alerts-frontend
      rules:
      - alert: Applikasjon nede
        expr: kube_deployment_status_replicas_available{deployment="\{{ APP_NAME }}"} == 0
        for: 2m
        annotations:
          consequence: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
          action: "`kubectl describe pod -l app={{ $labels.app }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.app }} -n {{ $labels.namespace }}` for logger"
        labels:
          namespace: etterlatte
          severity: critical