apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: etterlatteytelser
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  pool: nav-prod
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 48  # -1 means unlimited
  acl:
    - team: etterlatte
      application: dodsfall-fra-leesah
      access: readwrite
    - team: etterlatte
      application: finn-etterlatte
      access: readwrite
    - team: etterlatte
      application: heartbeat
      access: readwrite
    - team: etterlatte
      application: sjekk-alder-etterlatte
      access: readwrite
    - team: etterlatte
      application: journalfoer-soeknad
      access: readwrite
    - team: etterlatte
      application: selvbetjening-api
      access: readwrite
    - team: etterlatte
      application: innsendt-soeknad
      access: readwrite
    - team: etterlatte
      application: sjekk-adressebeskyttelse
      access: readwrite
    - team: etterlatte
      application: journalpost-info
      access: readwrite
    - team: etterlatte
      application: etterlatte-kafka-manager
      access: read
    - team: etterlatte
      application: bpc-explorer
      access: read
    - team: etterlatte
      application: etterlatte-notifikasjoner
      access: readwrite