export enum NedtellingsMelding {
    REGISTRER_NEDTELLINGS_LYTTER = 'REGISTRER_NEDTELLINGS_LYTTER',
    OPPDATER_NEDTELLINGS_LYTTER = 'OPPDATER_NEDTELLINGS_LYTTER',
    FJERN_NEDTELLINGS_LYTTER = 'FJERN_NEDTELLINGS_LYTTER',
    NEDTELLINGS_NOTIFIKASJON = 'NEDTELLINGS_NOTIFIKASJON',
}
