apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-backend
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: internal/isalive
  readiness:
    initialDelay: 5
    path: internal/isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: selvbetjening-backend
        tier: db-g1-small
        databases:
          - name: selvbetjening-backend
            envVarPrefix: DB
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: "dev-fss:pdl:pdl-api"
    - name: ETTERLATTE_API_URL
      value: http://etterlatte-api:etterlatte
    - name: ETTERLATTE_API_AUDIENCE
      value: dev-gcp:etterlatte:etterlatte-api
  accessPolicy:
    outbound:
      rules:
        - application: etterlatte-api
          namespace: etterlatte
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: selvbetjening-ui