apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-backend
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /internal/isalive
  readiness:
    initialDelay: 5
    path: /internal/isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: selvbetjening-backend
        tier: db-f1-micro
        databases:
          - name: selvbetjening-backend
            envVarPrefix: DB
  resources:
    requests:
      cpu: 20m
      memory: 320Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
  accessPolicy:
    inbound:
      rules:
        - application: selvbetjening-ui