apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-notifikasjoner
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
    #beskjedTopic: aapen-brukernotifikasjon-nyBeskjed-v1
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  envFrom:
    - secret: barnepensjon-secrets
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    #- name: BRUKERNOTIFIKASJON_KAFKA_BROKERS # Er dette de riktige?
    #  value: "b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443"
    #- name: BRUKERNOTIFIKASJON_KAFKA_SCHEMA_REGISTRY
    #  value: "https://kafka-schema-registry.nais-q.adeo.no/"
    - name: BRUKERNOTIFIKASJON_KAFKA_GROUP_ID
      value: "etterlatte-v1"
    - name: BRUKERNOTIFIKASJON_BESKJED_TOPIC
      value: "min-side.aapen-brukernotifikasjon-beskjed-v1"
  accessPolicy:
    outbound:
      external:
        - host: "kafka-schema-registry.nais-q.adeo.no"