apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-notifikasjoner
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: BRUKERNOTIFIKASJON_KAFKA_BROKERS
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
    - name: BRUKERNOTIFIKASJON_KAFKA_SCHEMA_REGISTRY
      value: "https://kafka-schema-registry.nais.adeo.no/"
    - name: BRUKERNOTIFIKASJON_KAFKA_GROUP_ID
      value: "etterlatte-v1"
    - name: BRUKERNOTIFIKASJON_BESKJED_TOPIC
      value: "aapen-brukernotifikasjon-nyBeskjed-v1"
  accessPolicy:
    outbound:
      external:
        - host: "kafka-schema-registry.nais.adeo.no"