apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omstillingsstoenad-ui
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - https://etterlatte.intern.dev.nav.no/omstillingsstonad/soknad
  liveness:
    path: /omstillingsstonad/soknad/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /omstillingsstonad/soknad/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 192Mi
  prometheus:
    enabled: true
    path: /omstillingsstonad/soknad/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: idporten-loa-high
      locale: nb
      autoLogin: true
  env:
    - name: BASE_PATH
      value: /omstillingsstonad/soknad
    - name: API_URL
      value: http://selvbetjening-api
    - name: AUDIENCE
      value: dev-gcp:etterlatte:selvbetjening-api
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: selvbetjening-api
        - application: nav-dekoratoren
          namespace: personbruker
