apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: barnepensjon-ui-tolk-locales-sanity
  namespace: team-tolk
  labels:
    team: team-tolk
spec:
  image: {{ image }}
  team: team-tolk
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  port: 3333
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
    liveness:
      path: /isAlive
      initialDelay: 5
    readiness:
      path: /isReady
      initialDelay: 5
  ingresses:
    - https://brukertest-ui-tolk-locales-sanity.dev.intern.nav.no