export enum CountdownMessage {
    REGISTER_COUNTDOWN_LISTENER = 'REGISTER_COUNTDOWN_LISTENER',
    UPDATE_COUNTDOWN_LISTENER = 'UPDATE_COUNTDOWN_LISTENER',
    REMOVE_COUNTDOWN_LISTENER = 'REMOVE_COUNTDOWN_LISTENER',
    COUNTDOWN_NOTIFICATION = 'COUNTDOWN_NOTIFICATION',
}
