---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: etterlatte-pdl-proxy
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  team: etterlatte
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  envFrom:
    - secret: barnepensjon-secrets
  env:
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_AUDIENCE
      value: "dev-fss:pdl:pdl-api"
    - name: PDL_OUTBOUND_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: finn-etterlatte
          namespace: etterlatte
          cluster: dev-gcp
        - application: sjekk-alder-etterlatte
          namespace: etterlatte
          cluster: dev-gcp
        - application: selvbetjening-api
          namespace: etterlatte
          cluster: dev-gcp
        - application: sjekk-adressebeskyttelse
          namespace: etterlatte
          cluster: dev-gcp
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io

