env:
    browser: true
    es2021: true
extends:
    # Kan også bruke DISABLE_ESLINT_PLUGIN=true
    #- 'eslint:recommended'
    #  - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    #- 'plugin:jsx-a11y/recommended'
    #- 'plugin:jest/recommended'
ignorePatterns:
    - 'node_modules/*'
    - 'nais/*'
    - 'build/*'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    #  - react
    - react-hooks
    - '@typescript-eslint'
    - 'jsx-a11y'
    - 'jest'
rules:
    {
        'react/react-in-jsx-scope': 'off',
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
    }
globals:
    'process': true
    'require': true
    'module': true
    '__dirname': true
settings:
    react:
        version: 17.0.2
