apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-ui
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - "https://etterlatteytelser.labs.nais.io"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  webproxy: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    clientUri: https://etterlatteytelser.labs.nais.io
    postLogoutRedirectURIs:
      - https://etterlatteytelser.labs.nais.io/logout/callback
  envFrom:
    - secret: redis-password
    - secret: session-encrypt-key
  env:
    - name: API_URL
      value: http://selvbetjening-api
    - name: REDIS_HOST
      value: selvbetjening-redis.dev.nais.io
    - name: SELVBETJENING_AUDIENCE
      value: dev-gcp:etterlatte:selvbetjening-api
    - name: NODE_LOG_LEVEL
      value: info
    - name: IDPORTEN_POST_LOGOUT_REDIRECT_URI
      value: https://etterlatteytelser.labs.nais.io/logout/callback
    - name: LOGINSERVICE_URL
      value: https://loginservice.dev.nav.no/login?redirect=https://etterlatteytelser.labs.nais.io
    - name: LOGINSERVICE_LOGOUT_URL
      value: https://loginservice.dev.nav.no/slo
  accessPolicy:
    outbound:
      external:
        - host: loginservice.dev.nav.no
        - host: dekoratoren.dev.nav.no
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: selvbetjening-api
          namespace: etterlatte
          cluster: dev-gcp
        - application: selvbetjening-redis
          namespace: etterlatte
          cluster: dev-gcp