apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sjekk-adressebeskyttelse
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: KAFKA_RESET_POLICY
      value: none
    - name: PDL_URL
      value: http://etterlatte-pdl-proxy/pdl
    - name: PDL_AZURE_SCOPE
      value: api://dev-gcp.etterlatte.etterlatte-pdl-proxy/.default
      #value: "https://etterlatte-proxy.dev-fss-pub.nais.io/pdl"
  accessPolicy:
    outbound:
      #external:
      #  - host: "https://etterlatte-proxy.dev-fss-pub.nais.io"
      rules:
        - application: etterlatte-pdl-proxy
