apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sjekk-adressebeskyttelse
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  resources:
    requests:
      cpu: 10m
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  env:
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
    - name: KAFKA_RESET_POLICY
      value: none
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
