apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: gjenlevendepensjon-ui
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - https://www.nav.no/gjenlevendepensjon/soknad
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /gjenlevendepensjon/soknad/metrics
  tokenx:
    enabled: true
  idporten:
    enabled: true
    clientUri: https://www.nav.no
    frontchannelLogoutPath: /gjenlevendepensjon/soknad/logout
    postLogoutRedirectURIs:
      - https://www.nav.no/gjenlevendepensjon/soknad/logout/callback
    accessTokenLifetime: 3600
    sessionLifetime: 3600
    sidecar:
      enabled: true
      level: idporten-loa-high
      locale: nb
      autoLogin: true
      errorPath: ""
  env:
    - name: BASE_PATH
      value: /gjenlevendepensjon/soknad
    - name: API_URL
      value: http://selvbetjening-api
    - name: AUDIENCE
      value: prod-gcp:etterlatte:selvbetjening-api
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: tokendings.prod-gcp.nais.io
      rules:
        - application: selvbetjening-api
        - application: nav-dekoratoren
          namespace: personbruker
