apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-api
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "internal/isalive"
    initialDelay: 40
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "internal/isready"
    initialDelay: 40
    timeout: 1
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: PDL_URL
      value: "https://etterlatte-proxy.dev-fss-pub.nais.io/pdl"
    - name: PDL_AUDIENCE
      value: "dev-fss:etterlatte:etterlatte-proxy"
    - name: KAFKA_RAPID_TOPIC
      value: etterlatte.dodsmelding
  ingresses:
    - "https://etterlatte-selvbetjening-api.dev.adeo.no"
  accessPolicy:
    outbound:
      rules:
        - application: etterlatte-proxy
    inbound:
      rules:
        - application: selvbetjening-ui