env:
  browser: true
  es2021: true
extends:
  # Kan også bruke DISABLE_ESLINT_PLUGIN=true 
  #- 'eslint:recommended'
  #- 'plugin:react/recommended'
  #- 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  #- 'plugin:jest/recommended'
ignorePatterns: 
  - 'node_modules/*'
  - 'nais/*'
  - 'build/*'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'jsx-a11y'
  - 'jest'
rules: {
     'react/react-in-jsx-scope': 'off',
     '@typescript-eslint/no-explicit-any': 'off',
     'react/prop-types': 'off',
     '@typescript-eslint/explicit-module-boundary-types': 'off',
     '@typescript-eslint/no-var-requires': 'off',
     '@typescript-eslint/no-empty-function': 'off'
}
globals: 
  'process': true
  'require': true
  'module': true
  '__dirname': true
settings: 
  react:
    version: 17.0.2