apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: barnepensjon-ui-tolk
  namespace: team-tolk
  labels:
    team: team-tolk
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - https://team-tolk.dev.nav.no/barnepensjon/soknad
  liveness:
    path: /barnepensjon/soknad/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /barnepensjon/soknad/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /barnepensjon/soknad/metrics
  tokenx:
    enabled: true
  idporten:
    enabled: true
    clientUri: https://www.dev.nav.no
    frontchannelLogoutPath: /barnepensjon/soknad/logout
    postLogoutRedirectURIs:
      - https://team-tolk.dev.nav.no/barnepensjon/soknad/logout/callback
    accessTokenLifetime: 3600
    sessionLifetime: 3600
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
  env:
    - name: BASE_PATH
      value: /barnepensjon/soknad
    - name: API_URL
      value: http://selvbetjening-api-tolk
    - name: AUDIENCE
      value: dev-gcp:team-tolk:selvbetjening-api-tolk
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: selvbetjening-api-tolk