name: .build-frontend.yaml

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Sti til dockerfile'
        required: true
        type: string
    outputs:
      image:
        description: "Docker image url"
        value: ${{ jobs.build-and-publish.outputs.image }}
      yarnlockhash:
        description: "Docker image url"
        value: ${{ jobs.build-and-publish.outputs.yarnlockhash }}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    if: github.event_name != 'pull_request'
    name: Build & publish
    runs-on: ubuntu-latest
    outputs:
      yarnlockhash: ${{ steps.keys.outputs.yarnlockhash }}
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      # Hash yarn.lock file to see if it has changed
      - name: Create hash from yarn.lock
        id: keys
        run: |
          HASHED=${{ hashFiles('apps/github.workflow/yarn.lock') }}
          echo $HASHED
          echo "yarnlockhash=${{ github.workflow }}-${{ hashFiles('apps/${{ github.workflow }}/yarn.lock') }}" >> "$GITHUB_OUTPUT"

      # Client cache
      - name: Cache node modules (client)
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            apps/${{ github.workflow }}/node_modules
            ~/.cache/Cypress
          key: ${{ steps.keys.outputs.yarnlockhash }}