name: .test-frontend.yaml

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  test-and-verify:
    name: Test and verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # ratchet:actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache npm modules webapp
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # ratchet:actions/cache@v5
        id: yarn-cache-webapp # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            apps/${{ github.workflow }}/node_modules
            ~/.cache/Cypress
          key: ${{ hashFiles(format('apps/{0}/yarn.lock',github.workflow)) }}

      # Install and build
      - name: Install & build bff
        working-directory: apps/etterlatte-node-server
        run: yarn install --frozen-lockfile && yarn build --outDir dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Install node modules webapp
        if: steps.yarn-cache-webapp.outputs.cache-hit != 'true'
        working-directory: apps/${{ github.workflow }}
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: build webapp
        working-directory: apps/${{ github.workflow }}
        run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      # Run tests
      - name: Run unit tests client
        working-directory: apps/${{ github.workflow }}
        run: CI=true yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run unit tests BFF
        working-directory: apps/etterlatte-node-server
        run: CI=true yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run e2e tests (Cypress) client
        uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # ratchet:cypress-io/github-action@v6
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          install: false
          start: yarn start
          wait-on: 'http://localhost:5173'
          working-directory: apps/${{ github.workflow }}
