name: Deploy alerts to NAIS
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - 'alerts-frontend.yaml'
      - 'alerts-backend.yaml'
      - '.github/workflows/alerts.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: deploy frontend to dev
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts-frontend.yaml
          VAR: LOGS_URL=https://logs.adeo.no/app/r/s/fptfa
      - name: deploy backend to dev
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts-backend.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/a777fa3577c1777d890c11a6f845bbc5?security_tenant=navlogs
      - name: deploy frontend to prod
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts-frontend.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/130a6a0221d3ea131ad5ceb17e28ec9a?security_tenant=navlogs
      - name: deploy backend to prod
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts-backend.yaml
          VAR: LOGS_URL=https://logs.adeo.no/app/r/s/Ojfw9
