name: Deploy alerts to NAIS
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - 'alerts-frontend.yaml'
      - 'alerts-backend.yaml'
      - '.github/workflows/alerts.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v6
      - name: deploy frontend to dev
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts-frontend.yaml
          VAR: LOGS_URL=https://logs.adeo.no/app/r/s/fptfa
      - name: deploy backend to dev
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts-backend.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/e50de3b91964f2cc53e69aa07a48e96e?security_tenant=navlogs
      - name: deploy frontend to prod
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts-frontend.yaml
          VAR: LOGS_URL=https://logs.az.nav.no/goto/7ce0886fddc960bdc9d19d0071e6f8f0?security_tenant=navlogs
      - name: deploy backend to prod
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts-backend.yaml
          VAR: LOGS_URL=https://logs.adeo.no/app/r/s/Ojfw9
