name: sjekk-adressebeskyttelse

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}:${{ github.sha }}
  APP_NAME: ${{ github.workflow }}

on:
  workflow_dispatch: # Allow manually triggered workflow run
    inputs:
      deploy-prod:
        description: 'Deploy til produksjon'
        required: false
        default: 'false'
  push:
    branches:
      - main
      - release/*
      - feature/*
    paths:
      - apps/sjekk-adressebeskyttelse/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/.deploy.yaml
    with:
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
