name: omstillingsstoenad-ui

on:
  workflow_dispatch: # Allow manually triggered workflow run
    inputs:
      deploy-prod:
        description: "Deploy til produksjon"
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
  push:
    branches:
      - main
    paths:
      - apps/omstillingsstoenad-ui/**
  pull_request:
    branches:
      - main
    paths:
      - apps/omstillingsstoenad-ui/**

jobs:
  build:
    uses: ./.github/workflows/.build-frontend.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  test:
    needs: build
    uses: ./.github/workflows/.test-frontend.yaml
    with:
      yarn-lock-hash: ${{ needs.build.outputs.yarn-lock-hash }}
    secrets: inherit

  # M책 byttes tilbake til 책 bruke deploy.yaml n책r vi g책r i prod
  deploy-to-dev-gcp:
    name: dev-gcp
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/${{ github.workflow }}/.nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
