name: omstillingsstoenad-ui

on:
  workflow_dispatch: # Allow manually triggered workflow run
    inputs:
      deploy-prod:
        description: "Deploy til produksjon"
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
  push:
    branches:
      - main
    paths:
      - apps/etterlatte-node-server/**
      - '!apps/etterlatte-node-server/src/mock/**'
      - '!apps/etterlatte-node-server/barnepensjon-ui/**'
      - '!apps/etterlatte-node-server/README.md'
  pull_request:
    branches:
      - main
    paths:

      - apps/etterlatte-node-server/**
      - '!apps/etterlatte-node-server/src/mock/**'
      - '!apps/etterlatte-node-server/barnepensjon-ui/**'
      - '!apps/etterlatte-node-server/README.md'

jobs:
  build:
    uses: ./.github/workflows/.deploy-frontend.yaml
    with:
      dockerfile: apps/etterlatte-node-server/Dockerfile
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.deploy-frontend.yaml
    with:
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
    permissions:
      contents: read
      id-token: write
