name: selvbetjening-backend

on:
  workflow_dispatch: # Allow manually triggered workflow run
    inputs:
      deploy-prod:
        description: 'Deploy til produksjon'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
  push:
    branches:
      - main
    paths:
      - apps/selvbetjening-backend/**
      - gradle/libs.versions.toml
      - buildSrc/**
  pull_request:
    branches:
      - main
    paths:
      - apps/selvbetjening-backend/**
      - gradle/libs.versions.toml
      - buildSrc/**

permissions:
  contents: write
  id-token: write

jobs:
  test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.test-backend.yaml
    secrets: inherit

  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.build-and-deploy-backend.yaml
    secrets: inherit
