name: brukerdialog-sanity

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - EY-4397-sanity-for-innledning-inntektsjustering
    paths:
      - apps/brukerdialog-sanity/**
      - .github/workflows/brukerdialog-sanity.yaml

jobs:
  deploy_sanity_studio:
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
    name: Deploy sanity studio
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Cache node modules
        uses: actions/cache@v4
        id: yarn-cache-webapp
        with:
          path: apps/${{ github.workflow }}/node_modules
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: apps/${{ github.workflow }}
        run: yarn install --frozen-lockfile
      - name: Deploy sanity studio
        working-directory: apps/${{ github.workflow }}
        run: yarn deploy

