name: test-lock-hash.yaml

on:
  push:
    branches:
      - lock-hash
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  hash:
    name: Create hash
    runs-on: ubuntu-latest
    outputs:
      ylh: ${{ steps.keys.outputs.ylh }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Hash yarn.lock file to see if it has changed
      - name: Create hash from yarn.lock
        id: keys
        run: |
          WORKFLOW=etterlatte-node-server
          echo "yarn-lock-hash=$WORKFLOW-${{ hashFiles('apps/$WORKFLOW/yarn.lock') }}" >> "$GITHUB_OUTPUT"

      # Client cache
      - name: Cache node modules (client)
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            apps/${{ github.workflow }}/node_modules
            ~/.cache/Cypress
          key: ${{ steps.keys.outputs.yarn-lock-hash }}