apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-api
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: internal/isalive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: internal/isready
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: internal/metrics
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: PDL_URL
      #value: "https://etterlatte-proxy.dev-fss-pub.nais.io/tokenx/pdl"
      value: http://etterlatte-pdl-proxy/pdl
    - name: PDL_AZURE_SCOPE
      value: api://dev-gcp.etterlatte.etterlatte-pdl-proxy/.default
    - name: PDL_AUDIENCE
      #value: "dev-fss:etterlatte:etterlatte-proxy"
      value: "dev-gcp:etterlatte:etterlatte-pdl-proxy"
    - name: INNSENDTSOEKNAD_AUDIENCE
      value: "dev-gcp:etterlatte:innsendt-soeknad"
    - name: ROOT_LOGLEVEL
      value: "INFO"
    - name: KODEVERK_URL
      value: "https://etterlatte-proxy.dev-fss-pub.nais.io/tokenx/kodeverk/"
    - name: KODEVERK_AUDIENCE
      value: "dev-fss:etterlatte:etterlatte-proxy"
    - name: NAV_CONSUMER_ID
      value: "srvbarnepensjon"
  accessPolicy:
    outbound:
      rules:
        #- application: etterlatte-proxy
        - application: etterlatte-pdl-proxy
        - application: innsendt-soeknad
    inbound:
      rules:
        - application: selvbetjening-ui