apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: selvbetjening-api
  namespace: etterlatte
  labels:
    team: etterlatte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: internal/isalive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: internal/isready
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: internal/metrics
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_AZURE_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_AUDIENCE
      value: "prod-fss:pdl:pdl-api"
    - name: INNSENDTSOEKNAD_AUDIENCE
      value: "prod-gcp:etterlatte:innsendt-soeknad"
    - name: ROOT_LOGLEVEL
      value: "INFO"
    - name: KODEVERK_URL
      value: "https://kodeverk.prod-fss-pub.nais.io/api/v1/kodeverk"
    - name: NAV_CONSUMER_ID
      value: "srvbarnepensjon"
    - name: KRR_ENDPOINT_URL
      value: "http://digdir-krr-proxy.team-rocket/rest/v1/"
    - name: KRR_SCOPE
      value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_AUDIENCE
      value: "prod-gcp:team-rocket:digdir-krr-proxy"
  accessPolicy:
    outbound:
      rules:
        - application: innsendt-soeknad
        - application: digdir-krr-proxy
          namespace: team-rocket
      external:
        - host: kodeverk.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
    inbound:
      rules:
        - application: gjenlevendepensjon-ui
        - application: barnepensjon-ui
